version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.2"
      ONLINE_MODE: "false"
      NETWORK_COMPRESSION_THRESHOLD: "-1"
    volumes:
      - ./data:/data
